require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Security/Eval:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/NumberedParameters:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
